# Generated by Django 5.2.12 on 2026-03-05 09:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Learner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auth_user_id', models.CharField(help_text='ID from OIDC/Authentik', max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('mode', models.CharField(choices=[('ELITE', 'Elite'), ('SCALE', 'Scale')], default='SCALE', max_length=10)),
                ('experience_level', models.CharField(choices=[('student', 'Student'), ('professional', 'Professional'), ('switcher', 'Switcher')], default='student', max_length=20)),
                ('timezone', models.CharField(default='UTC', max_length=100)),
                ('locale', models.CharField(default='en', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
