# Generated by Django 5.2.12 on 2026-03-07 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='learner',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
    ]
