# Generated by Django 5.2.12 on 2026-03-07 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_learner_phone_number_learner_profile_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
