# Generated by Django 5.2.12 on 2026-03-10 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_learner_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
