# Generated by Django 5.2.12 on 2026-03-05 09:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.FloatField(default=0.0)),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_mentor_reviews', to='accounts.learner')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_mentor_reviews', to='accounts.learner')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.track')),
            ],
        ),
        migrations.CreateModel(
            name='PeerReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.FloatField(default=0.0)),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_peer_reviews', to='accounts.learner')),
                ('peer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_peer_reviews', to='accounts.learner')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.track')),
            ],
        ),
        migrations.CreateModel(
            name='ReadinessSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('knowledge_score', models.FloatField(default=0.0)),
                ('project_score', models.FloatField(default=0.0)),
                ('deployment_score', models.FloatField(default=0.0)),
                ('agent_score', models.FloatField(default=0.0)),
                ('peer_score', models.FloatField(default=0.0)),
                ('mentor_score', models.FloatField(default=0.0)),
                ('overall_score', models.FloatField(default=0.0)),
                ('graduation_eligible', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('as_of', models.DateTimeField(auto_now_add=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readiness_snapshots', to='accounts.learner')),
            ],
            options={
                'ordering': ['-as_of'],
            },
        ),
    ]
