# Generated by Django 5.2.12 on 2026-03-06 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readiness', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readinesssnapshot',
            name='agent_score',
        ),
        migrations.RemoveField(
            model_name='readinesssnapshot',
            name='deployment_score',
        ),
        migrations.RemoveField(
            model_name='readinesssnapshot',
            name='project_score',
        ),
        migrations.AddField(
            model_name='readinesssnapshot',
            name='validated_score',
            field=models.FloatField(default=0.0, help_text='AI validated assessment score'),
        ),
    ]
