# Generated by Django 5.2.12 on 2026-03-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackenrollment',
            name='personalized_summary',
            field=models.TextField(blank=True, help_text="Summary of how this curriculum relates to the learner's existing background (extracted via AI analysis)"),
        ),
    ]
