# Generated by Django 5.2.12 on 2026-03-07 09:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_learner_resume'),
        ('curriculum', '0002_trackenrollment_personalized_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalizedLessonContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(help_text='Personalized AI content for this specific learner')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personalized_lessons', to='accounts.learner')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personalized_contents', to='curriculum.lesson')),
            ],
            options={
                'unique_together': {('lesson', 'learner')},
            },
        ),
    ]
