# Generated by Django 5.2.12 on 2026-03-11 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_roadmap_roadmapstep_roadmapenrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmap',
            name='is_finalized',
            field=models.BooleanField(default=False),
        ),
    ]
