"""
Django settings for REMLearners_Backend project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-lzm6lsbdl#mt1y9wljcw=rst=bgu78yqh2(0q#$cr09=t^&l6+')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '[::1]']

# Security Settings for OIDC
SECURE_CROSS_ORIGIN_OPENER_POLICY = None # Allows the popup/redirect flow to work smoothly


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party apps
    'rest_framework',
    'corsheaders',
    'mozilla_django_oidc',

    # Local apps
    'apps.accounts',
    'apps.curriculum',
    'apps.readiness',
    'apps.ai_generation',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware', # Disabled for Safari/Local-dev cross-port compatibility
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://localhost:3000",
]
CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
]

ROOT_URLCONF = 'REMLearners_Backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'REMLearners_Backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'remlearners_db'),
        'USER': os.getenv('DB_USER', 'remlearners_user'),
        'PASSWORD': os.getenv('DB_PASSWORD', 'remlearners_password'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}

# External Services
GOOGLE_API_KEY = os.getenv('GOOGLE_API_KEY')


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# REST Framework Settings
# Note: We use a custom class to skip CSRF checks only for local development
from rest_framework.authentication import SessionAuthentication

class UnsafeSessionAuthentication(SessionAuthentication):
    def enforce_csrf(self, request):
        return  # Disable CSRF check

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'REMLearners_Backend.settings.UnsafeSessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ),
}

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]

# Use the session for CSRF storage (Cleaner for React apps)
CSRF_USE_SESSIONS = True
CSRF_COOKIE_HTTPONLY = False 

# Cookie settings for local dev cross-port
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication Backends
AUTHENTICATION_BACKENDS = (
    'apps.accounts.auth.AuthentikOIDCBackend',
    'django.contrib.auth.backends.ModelBackend',
)

# OIDC Settings
OIDC_RP_CLIENT_ID = os.getenv('AUTHENTIK_CLIENT_ID')
OIDC_RP_CLIENT_SECRET = os.getenv('AUTHENTIK_CLIENT_SECRET')

# Crucial: Ask Authentik for group memberships
OIDC_RP_SCOPES = "openid email profile groups"

# Using the exact endpoints provided by Authentik UI
AUTHENTIK_BASE_URL = os.getenv('AUTHENTIK_URL', 'http://localhost:9000')
OIDC_OP_AUTHORIZATION_ENDPOINT = f"{AUTHENTIK_BASE_URL}/application/o/authorize/"
OIDC_OP_TOKEN_ENDPOINT = f"{AUTHENTIK_BASE_URL}/application/o/token/"
OIDC_OP_USER_ENDPOINT = f"{AUTHENTIK_BASE_URL}/application/o/userinfo/"
OIDC_OP_JWKS_ENDPOINT = f"{AUTHENTIK_BASE_URL}/application/o/remlearner/jwks/"

OIDC_RP_SIGN_ALGO = 'RS256'
OIDC_STORE_ACCESS_TOKEN = True
OIDC_STORE_ID_TOKEN = True
OIDC_RP_CALLBACK_URL = 'http://localhost:8000/api/oidc/callback/'

LOGIN_REDIRECT_URL = "http://localhost:5173/"
LOGOUT_REDIRECT_URL = "http://localhost:5173/login"
LOGIN_URL = "/api/oidc/authenticate/"

# Session/Cookie settings for local OIDC
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = False  # Set to True in production with HTTPS
CSRF_COOKIE_SECURE = False
CSRF_COOKIE_HTTPONLY = False   # Allow JS to read the cookie for CSRF headers
